<footer>
  <div class="container">
    <p class="pull-left">
      Generated by <a href="http://code.google.com/p/doclava/">Doclava</a>.
    </p>
    <p class="pull-right">
      <a href="#">Back to top</a>
    </p>
  </div>
</footer><!-- footer -->
